port: 7880
bind_addresses: ["0.0.0.0"]

rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 60000
  use_external_ip: true

redis:
  address: 127.0.0.1:6379

keys:
  # matches LIVEKIT_API_KEY / LIVEKIT_API_SECRET in .env
  devkey: 9WoPUzuRHXTnUt256qUXcqd4lZ9LDFB5MiYRm6TQ

logging:
  level: info
