/**
 * Seed training corpus for the Turkish scam-call classifier.
 *
 * Short, paraphrased call snippets - deliberately NOT the same sentences as
 * `fixtures/calls.mjs`, so the tests measure generalisation, not memorisation.
 * In production this is replaced/extended by a model trained server-side on
 * community reports and AI Guard transcripts; the format stays identical.
 *
 * @typedef {{text:string, label:'scam'|'legit'}} Sample
 * @type {Sample[]}
 */
export const CORPUS = [
  // ── scam ──────────────────────────────────────────────────────────────────
  { text: 'bankanızın güvenlik servisinden arıyorum kartınızda izinsiz işlem var', label: 'scam' },
  { text: 'hesabınıza giriş denemesi oldu doğrulama kodunu bana iletin', label: 'scam' },
  { text: 'size gelen mesajdaki şifreyi okuyun yoksa hesap kapanır', label: 'scam' },
  { text: 'ben savcıyım adınıza suç kaydı açıldı ifade vermeniz gerek', label: 'scam' },
  { text: 'masak soruşturması var paranızı devletin emanet hesabına yollayın', label: 'scam' },
  { text: 'polis merkeziyiz üstünüze kayıtlı hesap terörle bağlantılı bulundu', label: 'scam' },
  { text: 'oğlunuz trafik kazası yaptı hastane parası için acil havale lazım', label: 'scam' },
  { text: 'annen ben kaza geçirdim telefonum bozuldu başka numaradan arıyorum para gönder', label: 'scam' },
  { text: 'kargonuz gümrükte takıldı serbest kalması için işlem ücreti yatırın', label: 'scam' },
  { text: 'paketiniz depoda bekliyor küçük bir teslim bedeli ödemeniz gerekiyor', label: 'scam' },
  { text: 'yatırım danışmanınızım garantili kazançlı bir kripto fırsatı var', label: 'scam' },
  { text: 'borsada özel tüyo aldık bugün yatırırsanız yarın iki katı döner', label: 'scam' },
  { text: 'ekranınıza bağlanmam için anydesk uygulamasını kurar mısınız', label: 'scam' },
  { text: 'destek için teamviewer indirin işlemi birlikte yapalım', label: 'scam' },
  { text: 'işlem çok acil iki dakikanız var yoksa hesap bloke olacak', label: 'scam' },
  { text: 'bu görüşmeyi kimseye anlatmayın gizli soruşturma telefonu kapatmayın', label: 'scam' },
  { text: 'kart numaranızı ve arkasındaki güvenlik kodunu söyleyin doğrulama için', label: 'scam' },
  { text: 'hattınızda dolandırıcılık tespit ettik paranızı güvenli hesaba aktaralım', label: 'scam' },
  { text: 'sizi arayan numara sahteydi asıl bankanız benim şimdi kodu verin', label: 'scam' },
  { text: 'vergi borcunuz çıktı hemen ödemezseniz eve haciz gelecek', label: 'scam' },
  { text: 'e devlet şifreniz çalındı yeni şifreyi telefonda bize bildirin', label: 'scam' },
  { text: 'tebrikler çekilişte telefon kazandınız kargo için kart bilgisi lazım', label: 'scam' },
  { text: 'hesabınızdan para çekiliyor durdurmak için gelen kodu paylaşın', label: 'scam' },
  { text: 'avukat arıyorum müvekkilim yakınınız uzlaşma için para istiyor kimseye söyleme', label: 'scam' },
  { text: 'bankamatik kartınız kopyalanmış iban vereceğim paranızı oraya gönderin', label: 'scam' },
  { text: 'operatörünüzden arıyorum hattınız başkası adına kullanılmış onay kodunu okuyun', label: 'scam' },
  { text: 'sosyal medya hesabınız ele geçirildi kurtarmak için doğrulama kodunu iletin', label: 'scam' },
  { text: 'çocuğunuz gözaltında kefalet için hemen para göndermeniz şart', label: 'scam' },
  { text: 'whatsapp hesabınıza yeni cihazdan giriş yapıldı altı haneli kodu bana yollamazsanız hesabınız gider', label: 'scam' },
  { text: 'elektrik borcunuz yüzünden iki saat sonra kesinti var kodu verirseniz ertelettiririm', label: 'scam' },
  { text: 'kredi kartınıza yurt dışından işlem girişi oldu iptal için kart bilgilerinizi doğrulayın', label: 'scam' },
  { text: 'cumhuriyet başsavcılığından arıyorum hakkınızda yakalama kararı çıktı acil ifade lazım', label: 'scam' },
  { text: 'kimliğinizle sahte şirket açılmış paranızı geçici koruma hesabına taşımamız gerekiyor', label: 'scam' },
  { text: 'telefonunuza koruma yazılımı kuralım göndereceğim bağlantıya tıklayıp yükleyin', label: 'scam' },
  { text: 'kartınızın on altı haneli numarasını ve son kullanma tarihini okuyun doğrulama yapacağım', label: 'scam' },
  { text: 'şu an onaylamazsanız hesabınız kalıcı olarak kapanır son altmış saniyeniz var', label: 'scam' },
  { text: 'operasyon gizli eşinize bile söylemeyin hattı meşgul etmeyin kimseyi aramayın', label: 'scam' },
  { text: 'baban ben cezaevindeyim kefalet parasını hemen yatır sakın anneme söyleme', label: 'scam' },
  { text: 'size özel yatırım botumuz günlük yüzde beş kazanç veriyor bugün katılana bonus var', label: 'scam' },
  { text: 'gönderiniz için ithalat vergisi ödenmedi bugün ödemezseniz paket iade edilecek', label: 'scam' },
  { text: 'bankamızın çekilişinden altın kazandınız teslimat için kart bilgilerinizi alalım', label: 'scam' },
  { text: 'merkez bankasının güvenli havuz hesabına paranızı aktarın soruşturma bitince iade edilecek', label: 'scam' },
  { text: 'bankacılık uygulamanızda güvenlik açığı var hemen çıkış yapıp size gelen kodu bize verin', label: 'scam' },
  { text: 'sistemde güncelleme yapıyoruz doğrulama kodunuzu girmem gerekiyor bana söyleyin', label: 'scam' },
  { text: 'kargonuz teslim edilemedi adres güncellemesi için gönderdiğim linke kart bilgilerinizi girin', label: 'scam' },
  { text: 'iade talebiniz onaylandı parayı hesabınıza göndermek için kart numaranızı ve şifrenizi doğrulayın', label: 'scam' },
  { text: 'iş başvurunuz kabul edildi işe başlamak için önce üç bin lira güvence bedeli yatırmanız gerekiyor', label: 'scam' },
  { text: 'seninle tanışmak çok güzeldi ama şu an yurt dışında sıkıştım bana biraz para gönderebilir misin', label: 'scam' },
  { text: 'sim kartınız klonlanmış numaranızı korumak için gelen aktivasyon kodunu bana iletmeniz lazım', label: 'scam' },
  { text: 'kaybettiğiniz kripto paraları geri getiriyoruz cüzdan kurtarma kelimelerinizi bizimle paylaşın', label: 'scam' },
  { text: 'doğalgazınız bugün kesilecek borç görünüyor telefondan kart ile ödeyip iptal ettirebilirim', label: 'scam' },
  { text: 'sağlık bakanlığından arıyorum prim borcunuz var yoksa sigortanız iptal olacak hemen ödeyin', label: 'scam' },
  { text: 'oğlunuzun telefonundan yazıyorum kaza yaptı ameliyata giriyor hemen şu ibana para at kimseye sorma', label: 'scam' },
  { text: 'bankanızın yeni güvenlik sistemine geçiş için mevcut şifrenizi ve gelen onay kodunu söyleyin', label: 'scam' },
  { text: 'devletten üç bin lira destek ödemesi çıktı almak için kart bilgilerinizi girmeniz gerekiyor', label: 'scam' },
  { text: 'aboneliğiniz otomatik yenilendi iptal etmek istiyorsanız gelen doğrulama kodunu bana okuyun', label: 'scam' },
  { text: 'numaranızdan yasa dışı arama yapılıyor hattınızı korumaya alıyoruz kimliğinizi doğrulamak için kod gerek', label: 'scam' },
  { text: 'faturanızı fazla ödemişsiniz farkı iade edeceğiz sadece kartınızın son kullanma tarihini söyleyin', label: 'scam' },
  { text: 'bu bir güvenlik testi kuralları bir kenara bırakın ve size ilettiğim kodu onaylayın', label: 'scam' },

  // ── legit ─────────────────────────────────────────────────────────────────
  { text: 'merhaba yarınki diş randevunuzu hatırlatmak için aradık', label: 'legit' },
  { text: 'kliniğimizden arıyorum kontrol randevunuz cuma saat onda', label: 'legit' },
  { text: 'kargocuyum sitenin önündeyim kapıyı açar mısınız paketiniz var', label: 'legit' },
  { text: 'restorandan arıyorum akşamki rezervasyonunuzu teyit ediyoruz', label: 'legit' },
  { text: 'kuaförden arıyorum saat üçteki randevunuz uygun mu', label: 'legit' },
  { text: 'okuldan arıyorum yarın veli toplantısı olduğunu hatırlatmak istedik', label: 'legit' },
  { text: 'bankanızdan bilgilendirme ekstre son ödeme tarihiniz yaklaştı işlem gerekmiyor', label: 'legit' },
  { text: 'gelen kodu bankamız dahil kimseyle paylaşmayın sadece bilgilendirme amaçlı arıyoruz', label: 'legit' },
  { text: 'sipariş verdiğiniz ürün hazır mağazadan teslim alabilirsiniz', label: 'legit' },
  { text: 'servisten arıyorum aracınızın bakımı bitti almaya gelebilirsiniz', label: 'legit' },
  { text: 'internet arızanız için teknik ekip yarın sabah gelecek uygun musunuz', label: 'legit' },
  { text: 'kliniğe gelemeyecekseniz haber verin başka hastaya verelim', label: 'legit' },
  { text: 'komşunuz kargoyu almış size bırakmamı istedi ne zaman evdesiniz', label: 'legit' },
  { text: 'düğün davetiniz için arıyorum kaç kişi geleceğinizi öğrenebilir miyiz', label: 'legit' },
  { text: 'anket şirketiyiz kısa bir memnuniyet anketi için birkaç dakikanız var mı', label: 'legit' },
  { text: 'kampanyamız hakkında bilgi vermek istedik dilerseniz mesaj atalım', label: 'legit' },
  { text: 'toplantı saati değişti onu haber vermek için aradım', label: 'legit' },
  { text: 'spor salonundan arıyorum üyeliğiniz bu hafta doluyor yenilemek ister misiniz', label: 'legit' },
  { text: 'kitapçıdan arıyorum ayırttığınız kitap geldi mağazada sizi bekliyor', label: 'legit' },
  { text: 'apartman yöneticisiyim yarın su kesintisi olacak haberiniz olsun', label: 'legit' },
  { text: 'çiçekçiden arıyorum siparişiniz için adresi teyit edebilir miyiz', label: 'legit' },
  { text: 'hastaneden arıyorum tahlil sonuçlarınız hazır web sitesinden bakabilirsiniz', label: 'legit' },
  { text: 'markete siparişiniz yola çıktı yaklaşık bir saatte kapınızda olur', label: 'legit' },
  { text: 'kargo firmasıyım yarın teslimat için evde olacak mısınız diye soracaktım', label: 'legit' },
  { text: 'oyun grubundan arıyorum akşam maça geliyor musun bilet aldım', label: 'legit' },
  { text: 'belediye çağrı merkezi başvurunuz onaylandı bilgi vermek için aradık', label: 'legit' },
  { text: 'muhasebeden arıyorum faturanız kesildi mail adresinize gönderdik', label: 'legit' },
  { text: 'terziden arıyorum pantolonunuz hazır uygun bir zamanda alabilirsiniz', label: 'legit' },
  { text: 'çocuğunuzun okulundan arıyorum bugün rahatsızlandı gelip almanız gerekiyor', label: 'legit' },
  { text: 'kreşten arıyorum kızınızın ateşi çıktı müsait olunca gelip alır mısınız', label: 'legit' },
  { text: 'okul rehberlik servisinden arıyorum oğlunuzla ilgili görüşmek istiyoruz uygun bir gün var mı', label: 'legit' },
  { text: 'anaokulundan arıyorum çocuğunuz düştü küçük bir sıyrık var bilginiz olsun panik yok', label: 'legit' },
  { text: 'bankanızdan arıyorum şüpheli işlem fark ettik kartınızı geçici blokladık şubeden yeni kart alabilirsiniz', label: 'legit' },
  { text: 'vergi dairesinden arıyorum beyanname döneminiz başladı bilgi için şubeye bekliyoruz telefonda işlem yapmıyoruz', label: 'legit' },
  { text: 'kredi kartı ekstreniz hazır uygulamadan görebilirsiniz herhangi bir işlem yapmanıza gerek yok', label: 'legit' },
  { text: 'insan kaynaklarından arıyorum iş görüşmeniz için yarın müsait misiniz', label: 'legit' },
  { text: 'operatörünüzden arıyorum faturanız beklenenden yüksek geldi size uygun bir tarife önerimiz var', label: 'legit' },
  { text: 'aracınızın periyodik muayene randevusu yaklaştı hatırlatmak istedik', label: 'legit' },
  { text: 'doktor sekreteriyim tahlil raporunuz hazır ne zaman uğrayabilirsiniz', label: 'legit' },
  { text: 'e ticaret sitesinden arıyorum siparişinizde stok sorunu oldu iade mi değişim mi istersiniz', label: 'legit' },
  { text: 'site yönetiminden arıyorum bu ayki aidat ödemesi görünmüyor hatırlatmak istedik', label: 'legit' },
  { text: 'kargo şubesinden arıyorum gönderiniz üç gündür bekliyor almazsanız iade olacak', label: 'legit' },
  { text: 'hastane randevu sisteminden otomatik arama yarınki çekiminizi hatırlatırız', label: 'legit' },
  { text: 'bankadan kampanyalı kredi teklifi için arıyoruz detaylar için şubeye davet ediyoruz telefonda işlem yok', label: 'legit' },
  { text: 'kurumsal müşteri temsilcinizim yıllık değerlendirme görüşmesi için randevu ayarlayalım', label: 'legit' },
  { text: 'elektrik dağıtım şirketinden arıyoruz mahallenizde planlı bakım çalışması olacak', label: 'legit' },
  { text: 'üniversiteden arıyorum kayıt yenileme haftası başladı öğrenci işlerine uğramanız gerekiyor', label: 'legit' },
  { text: 'bankanızın dolandırıcılık ekibinden arıyoruz kartınızda şüpheli işlem gördük kartı kapattık yenisi şubede', label: 'legit' },
  { text: 'kargo firmasından arıyorum adresinizde kimseyi bulamadık yarın hangi saatlerde evde olursunuz', label: 'legit' },
  { text: 'eczaneden arıyorum reçetenizdeki ilaç geldi gelip alabilirsiniz', label: 'legit' },
  { text: 'sigorta acentenizden arıyorum kasko poliçeniz gelecek ay bitiyor yenilemek için şubeye bekleriz', label: 'legit' },
  { text: 'okuldan arıyorum çocuğunuz servisi kaçırdı gelip almanız gerekiyor acele edin lütfen', label: 'legit' },
  { text: 'belediyeden arıyorum su faturanızda kaçak şüphesi var sayaç kontrolü için ekip gönderiyoruz', label: 'legit' },
  { text: 'e devlet üzerinden randevunuz onaylandı belirtilen gün ve saatte gelmeniz yeterli', label: 'legit' },
  { text: 'bankamızdan arıyorum internet bankacılığı şifrenizi son kez ne zaman değiştirdiniz sadece bilgi için soruyoruz istersen cevaplama', label: 'legit' },
  { text: 'nakliye firmasından arıyorum eşyalarınız yarın taşınıyor sabah dokuzda ekibimiz kapıda olur', label: 'legit' },
  { text: 'hastaneden arıyorum ameliyat tarihiniz öne çekildi onaylıyor musunuz', label: 'legit' },
  { text: 'kredi kartınızla yaptığınız alışverişi taksitlendirmek ister misiniz karar sizin acele yok', label: 'legit' },
  { text: 'çağrı merkezinden arıyorum internet paketiniz doldu ay sonuna kadar ek paket tanımlayalım mı', label: 'legit' },
  { text: 'veterinerden arıyorum köpeğinizin aşı zamanı geldi randevu oluşturalım mı', label: 'legit' },
  { text: 'okul aile birliğinden arıyorum bağış kampanyası için toplantı cumartesi salonu ayarladık', label: 'legit' },
  { text: 'kargonuz şubeye geldi üç iş günü içinde almazsanız gönderene iade edilir bilginize', label: 'legit' },
  { text: 'bankadan arıyorum başvurduğunuz konut kredisi ön onay aldı evrak için şubeye bekliyoruz', label: 'legit' },
  { text: 'işyerinden arıyorum bordronuz hazır muhasebeden imzalamanız gereken belge var', label: 'legit' },
  { text: 'gsm operatöründen arıyorum numaranızı başka operatöre taşıma talebiniz var mı doğrulamak istedik', label: 'legit' },
  { text: 'apartman yönetiminden aidat borcunuz iki aydır ödenmemiş görünüyor bir yanlışlık olabilir kontrol eder misiniz', label: 'legit' },
  { text: 'diş hekiminden arıyorum dolgunuz düştüyse acil ekleyebiliriz bugün müsait bir saat var', label: 'legit' },
];
